force_keyboard_focus = true
selection_wrap = true
theme = "kojarchy"
hide_action_hints = true

[placeholders]
"default" = { input = " Search...", list = "No Results" }

[keybinds]
quick_activate = []

[providers]
max_results = 256
default = [
  "desktopapplications",
]

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"
